import { useState, useEffect } from "react";
import { CheckCircle2Icon, ShieldAlertIcon, ShieldCheckIcon } from "lucide-react";

import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";

export const PolicyStatusPill = () => {
    return (
        <Popover>
            <PopoverTrigger asChild>
                <button
                    className={cn(
                        "flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-medium border transition-all select-none",
                        "bg-emerald-500/10 text-emerald-500 border-emerald-500/30 hover:bg-emerald-500/20"
                    )}
                >
                    <ShieldCheckIcon className="size-3 shrink-0" />
                    <span>Compliant with uploaded network & security policies</span>
                </button>
            </PopoverTrigger>
            <PopoverContent className="w-80 p-4" align="end">
                <div className="space-y-4">
                    <div>
                        <h4 className="font-medium text-sm flex items-center gap-2">
                            <ShieldCheckIcon className="size-4 text-emerald-500" />
                            Compliance Report
                        </h4>
                        <p className="text-xs text-muted-foreground mt-1">
                            All infrastructure code generated by Sereno IDE complies with current corporate policies.
                        </p>
                    </div>
                    <div className="space-y-2">
                        <h5 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                            Enforced Rules
                        </h5>
                        <ul className="space-y-2">
                            <li className="flex gap-2 text-sm items-start">
                                <CheckCircle2Icon className="size-4 text-emerald-500 shrink-0 translate-y-[2px]" />
                                <span className="leading-tight">All S3 buckets are private and encrypted at rest (AES-256).</span>
                            </li>
                            <li className="flex gap-2 text-sm items-start">
                                <CheckCircle2Icon className="size-4 text-emerald-500 shrink-0 translate-y-[2px]" />
                                <span className="leading-tight">VPC Flow Logs enabled for all subnets.</span>
                            </li>
                            <li className="flex gap-2 text-sm items-start">
                                <CheckCircle2Icon className="size-4 text-emerald-500 shrink-0 translate-y-[2px]" />
                                <span className="leading-tight">No public ingress rules (0.0.0.0/0) allowed on port 22 or 3389.</span>
                            </li>
                            <li className="flex gap-2 text-sm items-start">
                                <CheckCircle2Icon className="size-4 text-emerald-500 shrink-0 translate-y-[2px]" />
                                <span className="leading-tight">IAM Roles follow principle of least privilege.</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </PopoverContent>
        </Popover>
    );
};
